// <auto-generated />
using CH6_4_Boostrap.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CH6_4_Boostrap.Migrations
{
    [DbContext(typeof(EmployeeContext))]
    [Migration("20230821075629_InitialDB")]
    partial class InitialDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CH6_4_Boostrap.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employee");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Department = "總經理室",
                            Email = "mary@gmailcom",
                            Mobile = "0922-111222",
                            Name = "Mary",
                            Title = "CEO"
                        },
                        new
                        {
                            Id = 2,
                            Department = "人事部",
                            Email = "david@gmailcom",
                            Mobile = "0933-111222",
                            Name = "David",
                            Title = "管理師"
                        },
                        new
                        {
                            Id = 3,
                            Department = "財務部",
                            Email = "rose@gmailcom",
                            Mobile = "0944-111222",
                            Name = "Rose",
                            Title = "經理"
                        },
                        new
                        {
                            Id = 4,
                            Department = "總經理室2",
                            Email = "mary@gmailcom",
                            Mobile = "0922-111222",
                            Name = "Mary2",
                            Title = "CEO2"
                        },
                        new
                        {
                            Id = 5,
                            Department = "人事部2",
                            Email = "david@gmailcom",
                            Mobile = "0933-111222",
                            Name = "David2",
                            Title = "管理師2"
                        },
                        new
                        {
                            Id = 6,
                            Department = "財務部2",
                            Email = "rose@gmailcom",
                            Mobile = "0944-111222",
                            Name = "Rose2",
                            Title = "經理2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
